/**
 * GSCN Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class DtoBankInfo { 
    bankName?: string;
    bankCode?: string;
    accountName?: string;
    branchName?: string;
    accountNumber?: string;
    branchEmail?: string;
    ifscCode?: string;
    micrCode?: string;
    notification?: boolean;
}