/**
 * GSCN Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class DtoContactDetails { 
    contactId?: number;
    line1?: string;
    line2?: string;
    city?: string;
    landMark?: string;
    postalCode?: string;
    district?: string;
}