/**
 * GSCN Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DtoBankInfo } from './dtoBankInfo';
import { DtoContactDetails } from './dtoContactDetails';
import { DtoEducationalDetails } from './dtoEducationalDetails';
import { DtoExperience } from './dtoExperience';
import { DtoFeesAndTiming } from './dtoFeesAndTiming';
import { DtoOtherInformation } from './dtoOtherInformation';

export class DtoDoctor { 
    title?: string;
    name?: string;
    type?: string;
    specialization?: string;
    myProperty?: number;
    registeredYear?: Date;
    registrationNo?: string;
    internationalBoard?: string;
    experience?: number;
    country?: number;
    email?: string;
    mobile?: string;
    dateOfBirth?: Date;
    gender?: number;
    aboutMe?: string;
    dtoBankInformations?: Array<DtoBankInfo>;
    dtoEducationalDetails?: Array<DtoEducationalDetails>;
    dtoContactInfo?: Array<DtoContactDetails>;
    dtoFeesAndTimings?: Array<DtoFeesAndTiming>;
    dtoExperienceDetails?: Array<DtoExperience>;
    dtoOtherInformation?: Array<DtoOtherInformation>;
}


//create the formcontrol object here 
//so that we can add the validation using the forms control object.
